apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra-apps
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: infra
    repoURL: 'https://github.com/robertzd/argo-k8s-lab'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true