---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://metallb.github.io/metallb'
    chart: metallb
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true