---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'metallb-system'
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/metallb
    repoURL: 'https://github.com/robertzd/argo-k8s-lab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true