apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-agent
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/portainer/agent
    repoURL: 'https://github.com/robertzd/argo-k8s-lab'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true