---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'traefik'
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 23.0.1
    chart: traefik
    helm:
      values: |-
        additionalArguments:
        deployemnt:
          replicas: 3
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            memory: 150Mi
        logs:
          general:
            level: ERROR
          access:
            enabled: true
        ports:
          web:
            redirectTo: websecure
          websecure:
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        ingressClass:
          enabled: true
          isDefaultClass: true
        service:
          type: LoadBalancer
          spec:
              loadBalancerIP: 172.16.16.50
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
